radius = input("Enter the radius of the sphere: ")
diameter = (float(radius) * 2)
circumference = (float(radius) * 3.14 * 2)
surfaceArea = (4 * 3.14 * float(radius) ** 2)
volume = ( 1.33 * 3.14 * float(radius) ** 3)
print("The diameter of the sphere is " + str(diameter) + " units.")
print("The circumference is " + str(circumference) + " units.")
print("The surface area of the sphere is " + str(surfaceArea) + " square units.")
print("The volume of the cube is " + str(volume) + " cubic units")
